project_parameters:
  email:
  project_id:
  feature_group_id:

autoscaler_parameters:
  launcher_queue: [PxPipeline_Launcher / PxPipeline_Launcher_gcp]

raven_query_parameters:
  modality: [radiology / pathology]
  dataset_id:
  organ_mask_type:
  organ_mask_provenance: [RAVEN-ETL / RAVEN-NIFTI]
  lesion_mask_type:
  lesion_mask_provenance: [RAVEN-ETL / RAVEN-NIFTI / RAVEN-ANGO]

pipeline_steps:
  - name: Step 1
    repo: https://github.com/Picture-Health/{step-1}.git
    branch:
    working_directory: .
    commit:
    script: pipeline_entrypoint.py
    output_path: desired/file/path
    execution_queue:
    parent_steps: []
    time_limit: 1800

  - name: Step 2
    repo: https://github.com/Picture-Health/{step-2}.git
    branch:
    working_directory: .
    commit:
    script: pipeline_entrypoint.py
    output_path: desired/file/path
    execution_queue:
    parent_steps: ['Step 1']
    time_limit: 1800

  - name: Step 3
    repo: https://github.com/Picture-Health/{step-3}.git
    branch:
    working_directory: .
    commit:
    script: pipeline_entrypoint.py
    output_path: desired/file/path
    execution_queue:
    parent_steps: ['Step 1']
    time_limit: 1800

  - name: Step 3
    repo: https://github.com/Picture-Health/{step-4}.git
    branch:
    working_directory: .
    commit:
    script: pipeline_entrypoint.py
    output_path: desired/file/path
    execution_queue:
    parent_steps: ['Step 2', 'Step 3']
    time_limit: 1800